spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/mini
    username: root
    password: 1234
  jpa:
    show-sql: true
    hibernate:
      jdbc:
        time_zone: Asia/Seoul
  mail:
    username:
    password:
  scheduling:
    enabled: true



